[versions]
kotlin = "2.3.10"
kotlinx-serialization = "1.6.3"

[libraries]
kotlinx-serialization-json  = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization ={ id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }